UPDATE subscription_plans SET price = 0, postings_limit = 1, post_listing_days = 30, support_level = 'Regular', post_assistance = 'No', referral_program = false, renewal = false, validity_days = 30 WHERE role_type = 'agent' AND tier = 'REGULAR';
UPDATE subscription_plans SET price = 499, postings_limit = 5, post_listing_days = 30, support_level = 'Regular', post_assistance = 'Yes', referral_program = false, renewal = true, validity_days = 90 WHERE role_type = 'agent' AND tier = 'GOLD';
UPDATE subscription_plans SET price = 999, postings_limit = 15, post_listing_days = 90, support_level = 'Premium', post_assistance = 'Premium', referral_program = true, renewal = true, validity_days = 365 WHERE role_type = 'agent' AND tier = 'PLATINUM';
UPDATE subscription_plans SET price = 1999, postings_limit = 50, post_listing_days = 180, support_level = 'Premium', post_assistance = 'Premium', referral_program = true, renewal = true, validity_days = 365 WHERE role_type = 'agent' AND tier = 'TITANIUM';

UPDATE subscription_plans SET price = 0, postings_limit = 1, post_listing_days = 30, support_level = 'Regular', post_assistance = 'No', referral_program = false, renewal = false, validity_days = 90, features = '{"display":"Local"}'::jsonb WHERE role_type = 'builder' AND tier = 'REGULAR';
UPDATE subscription_plans SET price = 9999, postings_limit = 10, post_listing_days = 90, support_level = 'Regular', post_assistance = 'Yes', referral_program = false, renewal = true, validity_days = 365, features = '{"display":"Pan India", "freeVerification":true}'::jsonb WHERE role_type = 'builder' AND tier = 'GOLD';
UPDATE subscription_plans SET price = 19999, postings_limit = 30, post_listing_days = 180, support_level = 'Premium', post_assistance = 'Premium', referral_program = false, renewal = true, validity_days = 365, features = '{"display":"Pan India", "freeVerification":true, "boostMode":true, "searchListing":true, "accountManager":true}'::jsonb WHERE role_type = 'builder' AND tier = 'PLATINUM';
UPDATE subscription_plans SET price = 39999, postings_limit = 100, post_listing_days = 365, support_level = 'Premium', post_assistance = 'Premium', referral_program = false, renewal = true, validity_days = 365, features = '{"display":"Pan India", "freeVerification":true, "boostMode":true, "searchListing":true, "accountManager":true}'::jsonb WHERE role_type = 'builder' AND tier = 'TITANIUM';
